### ISSUE TITLE
protoc-gen-json: options are omitted

### ISSUE THREAD

**Issue by srenatus** [sourcegraph/prototools#16]
When looking at the `protoc-gen-json` output of
```
protoc -I. -Ivendor/github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis/ --json_out=$(pwd)/out components/automate-gateway/api/iam/v2beta/policy.proto
```
run with [this file](https://github.com/chef/automate/blob/b0f892bdddfe3e739e0b3a422a162f2f0b86d66b/components/automate-gateway/api/iam/v2beta/policy.proto), I see most of what I'd expect to see, but all the `options` fields a empty. For example,
```
      "service": [
        {
          "name": "Policies",
          "method": [
            {
              "name": "CreatePolicy",
              "input_type": ".chef.automate.api.iam.v2beta.CreatePolicyReq",
              "output_type": ".chef.automate.api.iam.v2beta.CreatePolicyResp",
              "options": {}
            },
```

Am I missing something? Is there a way to have the options dumped as well? I do believe all the information should be in the CodeGenerationRequest 🤔

**Comment by srenatus** [comment]
Hah it's probably what was [noted here](https://github.com/sourcegraph/prototools/blob/b54ce590735f46af87984528ed4853827ef190cb/README.md#protoc-gen-dump):
> If you wish to retain e.g. grpc-gateway google.api.http annotations, you'll need to make use of protoc-gen-dump instead of protoc-gen-json.

Sorry for the noise. 😄

**Comment by srenatus** [comment]
At any rate, I'm still curious what an annotation needs to _do_ to be json-encodable... Can you enlighten me? 😃

**Comment by keegancsmith** [comment]
^^ cc @slimsag
