### ISSUE TITLE
Plugin failed with status code 1

### ISSUE THREAD

**Issue by nickpro** [sourcegraph/prototools#17]
Hello!
I'm unable to generate json from valid proto3 file. Here is my command and output
`protoc --json_out=/my/best/dir/proto/ valid_messages.proto`
`protoc-gen-json: program not found or is not executable
--json_out: protoc-gen-json: Plugin failed with status code 1.`

Also, --json-out docstring is missing from protoc --help output.
Can you tell me some steps to figure out the problem?
Thanks!

**Comment by unknwon** [comment]
"program not found or is not executable" looks like you have something not installed (but I don't know which)

**Comment by slimsag** [comment]
Probably you didn't follow installation steps for protoc-gen-json here: https://github.com/sourcegraph/prototools/blob/master/README.json.md#installation

Or, if you did, maybe you don't have your $GOBIN directory on your system $PATH?

**Comment by nickpro** [comment]
Fixed, thanks!

I hadn't configured $GOBIN, so plugin wasn't able to install properly, and all this happened pretty quiet :D

Thank you!
