### ISSUE TITLE
build protoc-gen-doc error

### ISSUE THREAD

**Issue by wwvm** [sourcegraph/prototools#21]
Three is an error raised while running 'go get -u sourcegraph.com/sourcegraph/prototools/cmd/protoc-gen-doc'
github.com/gengo/grpc-gateway/protoc-gen-grpc-gateway/descriptor/types.go:8:2: use of internal package github.com/grpc-ecosystem/grpc-gateway/internal/casing not allowed

go version: go1.14.3 linux/amd64

**Comment by keegancsmith** [comment]
Fixed in 4ba24e49a56785be77b572eb29541d86fec926a7
